apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: stateless-apps
spec:
  template:
    metadata:
      labels:
        payments-team: pay-team
      annotations:
        site.com/owner: "pay-team"
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: security-hardened
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64", "arm64"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t", "m", "c"]
  disruption:
    consolidationPolicy: WhenUnderutilized
    consolidateAfter: 30s
    budgets:
      - nodes: "10%"
  limits:
    cpu: "${cpu_limit}"
    memory: "${memory_limit}"